# Generated by Django 5.1.5 on 2025-02-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_created_at_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
    ]
