# Generated by Django 5.1.5 on 2025-02-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_offer_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
